# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.
require 'combustion'

Combustion.path = 'spec/test_app'
Combustion.initialize! :all
Combustion::Application.load_tasks